on:
  push:
    branches:
      - sync
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SIMA_FTP_SERVER }}
          username: ${{ secrets.SIMA_FTP_USERNAME }}
          password: ${{ secrets.SIMA_FTP_PASS }}
          local-dir: ./sync_test/
          server-dir: /public_html/sync_test/
